CREATE TABLE IF NOT EXISTS teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  telegram_link TEXT,
  average_rating NUMERIC(4, 2) DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS curators (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  telegram_link TEXT,
  average_rating NUMERIC(4, 2) DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  grade INTEGER CHECK (grade BETWEEN 1 AND 11 OR grade IS NULL),
  profile_status TEXT NOT NULL DEFAULT 'focused',
  active_badge_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  auth_token TEXT,
  auth_expires_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  auth_token TEXT,
  auth_expires_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('Teacher', 'Curator')),
  teacher_id INTEGER REFERENCES teachers(id) ON DELETE CASCADE,
  curator_id INTEGER REFERENCES curators(id) ON DELETE CASCADE,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  auth_token TEXT,
  auth_expires_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (role = 'Teacher' AND teacher_id IS NOT NULL AND curator_id IS NULL)
    OR
    (role = 'Curator' AND curator_id IS NOT NULL AND teacher_id IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  short_description TEXT,
  description TEXT,
  subject TEXT,
  teacher_id INTEGER REFERENCES teachers(id),
  curator_id INTEGER REFERENCES curators(id),
  total_lessons INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Archived')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS course_enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Paused', 'Finished', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, student_id)
);

CREATE TABLE IF NOT EXISTS parents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  telegram_link TEXT,
  vk_link TEXT,
  source_platform TEXT,
  comment_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_parents (
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  parent_id INTEGER NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
  relation_type TEXT NOT NULL DEFAULT 'Родитель',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (student_id, parent_id)
);

CREATE TABLE IF NOT EXISTS lessons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  lesson_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  topic TEXT,
  video_url TEXT,
  notes_url TEXT,
  homework_url TEXT,
  duration_minutes INTEGER DEFAULT 90,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Done', 'Homework_Check', 'Open', 'Announcement', 'Soon')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, lesson_number)
);

CREATE TABLE IF NOT EXISTS lesson_progress (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_enrollment_id INTEGER NOT NULL REFERENCES course_enrollments(id) ON DELETE CASCADE,
  lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  watch_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  UNIQUE (course_enrollment_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  material_type TEXT NOT NULL DEFAULT 'Конспект',
  author TEXT,
  file_url TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, lesson_id, material_type)
);

CREATE TABLE IF NOT EXISTS homework_templates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE SET NULL,
  teacher_id INTEGER REFERENCES teachers(id),
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT,
  max_score INTEGER NOT NULL DEFAULT 10 CHECK (max_score = 10),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS homework_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INTEGER NOT NULL REFERENCES homework_templates(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  enrollment_id INTEGER REFERENCES course_enrollments(id) ON DELETE SET NULL,
  teacher_id INTEGER REFERENCES teachers(id),
  due_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'Assigned' CHECK (status IN ('Assigned', 'Submitted', 'Checked', 'Cancelled')),
  upload_folder_link TEXT,
  teacher_comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (template_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL UNIQUE REFERENCES homework_assignments(id) ON DELETE CASCADE,
  student_text TEXT,
  file_url TEXT,
  status TEXT NOT NULL DEFAULT 'Submitted' CHECK (status IN ('Submitted', 'Checked')),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  checked_by_teacher_id INTEGER REFERENCES teachers(id),
  checked_at TIMESTAMPTZ,
  score INTEGER CHECK (score BETWEEN 1 AND 10 OR score IS NULL),
  feedback_text TEXT,
  feedback_url TEXT
);

CREATE TABLE IF NOT EXISTS homework_corrections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL UNIQUE REFERENCES homework_assignments(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  teacher_id INTEGER REFERENCES teachers(id),
  enrollment_id INTEGER REFERENCES course_enrollments(id) ON DELETE SET NULL,
  required_score INTEGER CHECK (required_score BETWEEN 1 AND 4 OR required_score IS NULL),
  status TEXT NOT NULL DEFAULT 'Required' CHECK (status IN ('Required', 'Submitted', 'Checked', 'Cancelled')),
  student_text TEXT,
  file_url TEXT,
  submitted_at TIMESTAMPTZ,
  checked_by_teacher_id INTEGER REFERENCES teachers(id),
  checked_at TIMESTAMPTZ,
  score INTEGER CHECK (score BETWEEN 1 AND 10 OR score IS NULL),
  feedback_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS point_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  enrollment_id INTEGER REFERENCES course_enrollments(id) ON DELETE SET NULL,
  homework_assignment_id INTEGER REFERENCES homework_assignments(id) ON DELETE SET NULL,
  correction_id INTEGER REFERENCES homework_corrections(id) ON DELETE SET NULL,
  points INTEGER NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_streams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  stream_link TEXT,
  record_link TEXT,
  status TEXT NOT NULL DEFAULT 'Planned' CHECK (status IN ('Planned', 'Live', 'Done', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_stream_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stream_id INTEGER NOT NULL REFERENCES live_streams(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  message_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff_resource_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_role TEXT NOT NULL CHECK (staff_role IN ('Teacher', 'Curator')),
  staff_id INTEGER NOT NULL,
  resource_type TEXT NOT NULL CHECK (resource_type IN ('Lesson', 'Note', 'Homework', 'Stream', 'Correction')),
  resource_id INTEGER NOT NULL,
  rating INTEGER CHECK (rating BETWEEN 1 AND 10 OR rating IS NULL),
  comment_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (staff_role, staff_id, resource_type, resource_id)
);

CREATE TABLE IF NOT EXISTS student_staff_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  staff_role TEXT NOT NULL CHECK (staff_role IN ('Teacher', 'Curator')),
  staff_id INTEGER NOT NULL,
  comment_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS course_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  preferred_subject TEXT NOT NULL,
  grade INTEGER CHECK (grade BETWEEN 1 AND 11 OR grade IS NULL),
  comment_text TEXT,
  source_page TEXT,
  status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Enrolled', 'Rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER REFERENCES students(id) ON DELETE SET NULL,
  topic TEXT,
  message_text TEXT,
  status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'In_Progress', 'Resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  admin_note TEXT
);

CREATE TABLE IF NOT EXISTS chats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  friend_student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  teacher_id INTEGER REFERENCES teachers(id) ON DELETE SET NULL,
  curator_id INTEGER REFERENCES curators(id) ON DELETE SET NULL,
  admin_id INTEGER REFERENCES admin_accounts(id) ON DELETE SET NULL,
  chat_type TEXT NOT NULL DEFAULT 'Legacy',
  target_role TEXT,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id INTEGER NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('Student', 'Teacher', 'Curator', 'Admin', 'System')),
  sender_name TEXT NOT NULL,
  message_text TEXT NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_friend_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  receiver_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Declined', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (requester_id <> receiver_id),
  UNIQUE (requester_id, receiver_id)
);

CREATE TABLE IF NOT EXISTS student_friends (
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  friend_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (student_id, friend_id),
  CHECK (student_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS curator_teachers (
  curator_id INTEGER NOT NULL REFERENCES curators(id) ON DELETE CASCADE,
  teacher_id INTEGER NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (curator_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS student_calls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curator_id INTEGER NOT NULL REFERENCES curators(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  call_link TEXT,
  starts_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'Planned' CHECK (status IN ('Planned', 'Done', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_call_participants (
  call_id INTEGER NOT NULL REFERENCES student_calls(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (call_id, student_id)
);

CREATE TABLE IF NOT EXISTS shop_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_code TEXT NOT NULL UNIQUE,
  item_name TEXT NOT NULL,
  item_type TEXT NOT NULL,
  audience TEXT NOT NULL DEFAULT 'All' CHECK (audience IN ('All', 'Teacher', 'Curator', 'Admin')),
  price_points INTEGER NOT NULL CHECK (price_points >= 0),
  css_class TEXT,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS profile_badges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  badge_code TEXT NOT NULL UNIQUE,
  badge_name TEXT NOT NULL,
  badge_type TEXT NOT NULL DEFAULT 'shop' CHECK (badge_type IN ('shop', 'achievement')),
  price_points INTEGER NOT NULL DEFAULT 0 CHECK (price_points >= 0),
  css_class TEXT,
  description TEXT,
  course_id INTEGER REFERENCES courses(id) ON DELETE SET NULL,
  unlock_percent INTEGER CHECK (unlock_percent BETWEEN 0 AND 100 OR unlock_percent IS NULL),
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS student_shop_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES shop_items(id) ON DELETE CASCADE,
  is_equipped BOOLEAN NOT NULL DEFAULT FALSE,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (student_id, item_id)
);

CREATE TABLE IF NOT EXISTS student_badges (
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  badge_id INTEGER NOT NULL REFERENCES profile_badges(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'achievement',
  unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (student_id, badge_id)
);

CREATE TABLE IF NOT EXISTS staff_point_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_role TEXT NOT NULL CHECK (staff_role IN ('Teacher', 'Curator', 'Admin')),
  staff_id INTEGER NOT NULL,
  points INTEGER NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff_shop_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_role TEXT NOT NULL CHECK (staff_role IN ('Teacher', 'Curator', 'Admin')),
  staff_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL REFERENCES shop_items(id) ON DELETE CASCADE,
  is_equipped BOOLEAN NOT NULL DEFAULT FALSE,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (staff_role, staff_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_courses_teacher ON courses(teacher_id);
CREATE INDEX IF NOT EXISTS idx_courses_curator ON courses(curator_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON course_enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_lessons_course ON lessons(course_id, lesson_number);
CREATE INDEX IF NOT EXISTS idx_assignments_student ON homework_assignments(student_id);
CREATE INDEX IF NOT EXISTS idx_assignments_template ON homework_assignments(template_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON homework_submissions(status, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_corrections_student ON homework_corrections(student_id, status);
CREATE INDEX IF NOT EXISTS idx_corrections_teacher ON homework_corrections(teacher_id, status);
CREATE INDEX IF NOT EXISTS idx_streams_course ON live_streams(course_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_stream_messages_stream ON live_stream_messages(stream_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reviews_resource ON staff_resource_reviews(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_comments_student ON student_staff_comments(student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_chat ON chat_messages(chat_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_friend_requests_receiver ON student_friend_requests(receiver_id, status);
CREATE INDEX IF NOT EXISTS idx_student_friends_friend ON student_friends(friend_id);
CREATE INDEX IF NOT EXISTS idx_student_parents_parent ON student_parents(parent_id);
CREATE INDEX IF NOT EXISTS idx_curator_teachers_curator ON curator_teachers(curator_id);
CREATE INDEX IF NOT EXISTS idx_curator_teachers_teacher ON curator_teachers(teacher_id);
CREATE INDEX IF NOT EXISTS idx_student_calls_curator ON student_calls(curator_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_student_call_participants_student ON student_call_participants(student_id);

ALTER TABLE students ADD COLUMN IF NOT EXISTS telegram_link TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS vk_link TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS source_platform TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS student_status TEXT NOT NULL DEFAULT 'Student';
ALTER TABLE students ADD COLUMN IF NOT EXISTS profile_status TEXT NOT NULL DEFAULT 'focused';
ALTER TABLE students ADD COLUMN IF NOT EXISTS active_badge_id INTEGER REFERENCES profile_badges(id) ON DELETE SET NULL;
ALTER TABLE point_transactions ADD COLUMN IF NOT EXISTS correction_id INTEGER REFERENCES homework_corrections(id) ON DELETE SET NULL;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS friend_student_id INTEGER REFERENCES students(id) ON DELETE CASCADE;

ALTER TABLE course_enrollments ADD COLUMN IF NOT EXISTS teacher_id INTEGER REFERENCES teachers(id);
ALTER TABLE course_enrollments ADD COLUMN IF NOT EXISTS curator_id INTEGER REFERENCES curators(id);

ALTER TABLE course_applications ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
ALTER TABLE course_applications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE course_applications ADD COLUMN IF NOT EXISTS admin_note TEXT;

ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS admin_note TEXT;
